### ISSUE TITLE
missing STREAM receipts spec

### ISSUE THREAD

**Issue by wilsonianb** [interledger/interledger-website#15] opened 2021-04-12 21:45 UTC
The [STREAM receipts spec](https://github.com/interledger/rfcs/blob/master/0039-stream-receipts/0039-stream-receipts.md) (which is [linked to](https://github.com/interledger/interledger-website/issues/14) in the [STREAM spec](https://interledger.org/rfcs/0029-stream/#4-life-of-a-connection)) is not available at https://interledger.org/rfcs/0039-stream-receipts/

**Comment by mccamon** [comment] 2021-04-13 19:32
This is a dupe of Issue 6

**Comment by mccamon** [comment] 2021-04-14 22:58
Duplicate of #6

**Closed by mccamon** 2021-04-14 22:58 UTC
Labels: bug
