### ISSUE TITLE
Broken spec links

### ISSUE THREAD

**Issue by wilsonianb** [interledger/interledger-website#14] opened 2021-04-12 21:42 UTC
Links in [specs](https://interledger.org/rfcs/0027-interledger-protocol-4/index.html) to other specs currently do not work.

For example, [Interledger Protocol V4](https://interledger.org/rfcs/0027-interledger-protocol-4/) links to https://interledger.org/rfcs/0025-pre-shared-key-2/0025-pre-shared-key-2.md instead of https://interledger.org/rfcs/0025-pre-shared-key-2/

**Comment by mccamon** [comment] 2021-04-13 19:32
This is a dupe of Issue 6

**Closed** 2021-04-14 22:57 UTC
Labels: bug
